export const urls = [
  'https://faq.myna.go.jp/?site_domain=default',
  /**
   * 下記URL取得できないため、コメントアウト
   */
  // 'https://myna.go.jp/svc/drivers-license',
  // 'https://myna.go.jp/family-registration',
  // 'https://myna.go.jp/settings/notification',
  // 'https://myna.go.jp/SCK1801_01_001/SCK1801_01_001_Reload.form',
  // 'https://myna.go.jp/settings/connection',
  // 'https://services.digital.go.jp/mynaportal/help/',
  // 'https://myna.go.jp/SCK0701_01_001/SCK0701_01_001_Init.form',
  // 'https://myna.go.jp/certificates/my-number-card',
  // 'https://myna.go.jp/receiving-account',
  // 'https://myna.go.jp/pension',
  // 'https://myna.go.jp/benefits',
  // 'https://myna.go.jp/tax',
  // 'https://myna.go.jp/svc/tax-return',
  // 'https://myna.go.jp/svc/year-end-adjustment',
  // 'https://myna.go.jp/certificates/health-insurance-card',
  // 'https://myna.go.jp/SCK2501_01_001/SCK2501_01_001_Reload.form',
  // 'https://myna.go.jp/medical-expenses',
  // 'https://myna.go.jp/certificates/medical-subsidy',
  // 'https://myna.go.jp/medicines',
  // 'https://myna.go.jp/vaccines',
  // 'https://myna.go.jp/child-checkup',
  // 'https://myna.go.jp/prenatal-checkups',
  // 'https://myna.go.jp/medical-conditions',
  // 'https://myna.go.jp/allergies-and-intolerances',
  // 'https://myna.go.jp/infection-lab-results',
  // 'https://myna.go.jp/medical-lab-results',
  // 'https://myna.go.jp/patient-referral-prescriptions',
  // 'https://myna.go.jp/svc/passport',
  // 'https://myna.go.jp/svc/employment-insurance',
];
